INSERT INTO TBL_PROVA(NAME, CUST, AREA) VALUES ('Glauco Todesco','20','5');
INSERT INTO TBL_PROVA(NAME, CUST, AREA) VALUES ('Maria Silva','3','2');
INSERT INTO TBL_PROVA(NAME, CUST, AREA) VALUES ('Fernanda Arruda','8','3');